name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create .env file
        run: |
          cat << EOF > .env
          # Database Configuration
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_TEST_PORT=${{ secrets.DB_TEST_PORT }}
          DB_TEST_NAME=${{ secrets.DB_TEST_NAME }}
          
          # PGAdmin
          PGADMIN_EMAIL=${{ secrets.PGADMIN_EMAIL }}
          PGADMIN_PASSWORD=${{ secrets.PGADMIN_PASSWORD }}
          
          # Grafana
          GRAFANA_USER=${{ secrets.GRAFANA_USER }}
          GRAFANA_PASSWORD=${{ secrets.GRAFANA_PASSWORD }}
          
          # Kafka (hardcoded)
          ENABLE_KAFKA=true
          KAFKA_BOOTSTRAP_SERVERS=localhost:9092
          SCHEMA_REGISTRY_URL=http://localhost:8081
          TOPIC_NAME=cryptics.thalex.instrument
          
          # Thalex API
          THALEX_KID_TEST=${{ secrets.THALEX_KID_TEST }}
          THALEX_KEY_TEST="${{ secrets.THALEX_KEY_TEST }}"
          EOF
      
      - name: Build and Deploy
        run: |
          cd docker
          docker-compose up -d